services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_HOST_URL: http://localhost:3005
    ports:
      - "4173:4173"
    environment:
      - VITE_API_HOST_URL=http://localhost:3005
    command: ["npx", "vite", "preview", "--host", "0.0.0.0"]
    networks:
      - app-network
    env_file:
      - ./frontend/client/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    networks:
      - app-network
    env_file:
      - ./backend/.env

networks:
  app-network:
    driver: bridge
